package com.muninalert.backend_munin_alert.service;

import java.util.List;
import java.util.Optional;

import com.muninalert.backend_munin_alert.model.Event;

/**
 * Service interface for managing events in the Munin Alert system.
 * 
 * This service provides methods for creating, retrieving, and analyzing
 * safety-related events generated by user devices and actions.
 */
public interface EventService {
    
    /**
     * Creates a new event in the system.
     * 
     * @param event The event object to create
     * @return The created event with generated ID
     */
    Event createEvent(Event event);
    
    /**
     * Finds an event by its unique identifier.
     * 
     * @param id The unique identifier of the event
     * @return An Optional containing the event if found, or empty if not found
     */
    Optional<Event> findEventById(String id);
    
    /**
     * Retrieves all events in the system.
     * 
     * @return A list of all events
     */
    List<Event> findAllEvents();
    
    /**
     * Finds all events for a specific user.
     * 
     * @param userId The ID of the user
     * @return A list of events for the user
     */
    List<Event> findEventsByUserId(String userId);
    
    /**
     * Finds all events of a specific type.
     * 
     * @param eventType The type of event
     * @return A list of events of the specified type
     */
    List<Event> findEventsByType(Event.EventType eventType);
    
    /**
     * Finds all events for a specific user and of a specific type.
     * 
     * @param userId The ID of the user
     * @param eventType The type of event
     * @return A list of events for the user and of the specified type
     */
    List<Event> findEventsByUserIdAndType(String userId, Event.EventType eventType);
    
    /**
     * Finds all events for a specific device.
     * 
     * @param deviceId The ID of the device
     * @return A list of events from the device
     */
    List<Event> findEventsByDeviceId(String deviceId);
    
    /**
     * Finds all events after a specific timestamp.
     * 
     * @param timestamp The timestamp in milliseconds
     * @return A list of events after the specified timestamp
     */
    List<Event> findEventsAfterTimestamp(long timestamp);
    
    /**
     * Finds all events for a specific user after a specific timestamp.
     * 
     * @param userId The ID of the user
     * @param timestamp The timestamp in milliseconds
     * @return A list of events for the user after the specified timestamp
     */
    List<Event> findEventsByUserIdAfterTimestamp(String userId, long timestamp);
    
    /**
     * Finds events with confidence score above a threshold.
     * 
     * @param confidenceThreshold The minimum confidence score (0.0-1.0)
     * @return A list of events with confidence above the threshold
     */
    List<Event> findEventsByMinimumConfidence(double confidenceThreshold);
    
    /**
     * Finds the most recent events for a user, limited by count.
     * 
     * @param userId The ID of the user
     * @param limit The maximum number of events to return
     * @return A list of the most recent events for the user
     */
    List<Event> findMostRecentEventsByUser(String userId, int limit);
    
    /**
     * Processes a new event and takes appropriate actions based on the event type.
     * This may include generating alerts, sending notifications, or updating user status.
     * 
     * @param event The event to process
     * @return The processed event
     */
    Event processNewEvent(Event event);
    
    /**
     * Deletes an event from the system.
     * 
     * @param id The unique identifier of the event to delete
     */
    void deleteEvent(String id);
    
    /**
     * Deletes events older than a specified timestamp.
     * 
     * @param timestamp The timestamp in milliseconds
     * @return The number of events deleted
     */
    int deleteEventsOlderThan(long timestamp);
}
