package com.muninalert.backend_munin_alert.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.Data;

/**
 * Model representing a safety-related event detected in the Munin Alert system.
 * 
 * Events are generated by device sensors and user actions, tracking incidents
 * such as falls, collisions, and manual alerts. These events can trigger
 * alerts and notifications based on their type and severity.
 */
@Data
@Document(collection = "events")
public class Event {
    /**
     * Unique identifier for the event.
     */
    @Id
    private String id;
    
    /**
     * ID of the user associated with this event.
     */
    private String userId;
    
    /**
     * ID of the device that detected or generated this event.
     */
    private String deviceId;
    
    /**
     * Type of event (e.g., fall detected, collision, manual alert).
     */
    private EventType eventType;
    
    /**
     * Geographic location where the event occurred.
     */
    private Location location;
    
    /**
     * Confidence score for automatically detected events (0.0 to 1.0).
     * Higher values indicate higher confidence in the accuracy of the detection.
     */
    private double confidence;
    
    /**
     * Raw sensor or application data related to the event.
     * This could include accelerometer readings, location history, etc.
     */
    private String rawData;
    
    /**
     * Timestamp when the event occurred (in milliseconds since epoch).
     */
    private long timestamp;
    
    /**
     * Enumeration of possible event types detected by the system.
     */
    public enum EventType {
        /** Automatically detected when a fall is detected by device sensors */
        FALL_DETECTED,
        /** Automatically detected when a collision is detected by device sensors */
        COLLISION_DETECTED,
        /** Automatically detected when rapid deceleration is detected */
        RAPID_DECELERATION,
        /** Automatically detected when unusual movement patterns are detected */
        UNUSUAL_MOVEMENT,
        /** Automatically detected when no activity is detected for a configured period */
        INACTIVITY,
        /** User manually triggered an alert from the application */
        MANUAL_ALERT,
        /** User entered a designated safe haven area */
        ENTER_SAFEHAVEN,
        /** User exited a designated safe haven area */
        EXIT_SAFEHAVEN,
        /** User entered an area with an active risk alert */
        ENTER_RISK_AREA,
        /** User exited an area with an active risk alert */
        EXIT_RISK_AREA
    }
}
